//! Deterministic test harness for the public commissioner API.
//!
//! The production commissioner lazily establishes DTLS and then exchanges
//! encrypted MeshCoP CoAP messages with a border agent. Most public API tests do
//! not need a real UDP socket, EC J-PAKE handshake, or record-protection state;
//! they need deterministic control over the request/response conversation after
//! DTLS has delivered application data.
//!
//! This harness scripts that post-DTLS MeshCoP layer. Each public API call still
//! builds a real [`crate::meshcop::CoapMessage`] and runs through the
//! production session driver (identity assignment, token correlation,
//! empty-ACK handling, retransmission, UDP_RX decapsulation, and notification
//! routing) over the scripted message stream. Crypto and wire-level DTLS behavior remain covered by the
//! dedicated `dtls` and `crypto` tests.
//!
//! This module is gated behind the `test-support` feature (and always built
//! under `cfg(test)`). It is unstable test scaffolding for this workspace's
//! suites, not a supported public API, and carries no stability guarantees.

use std::collections::VecDeque;
use std::net::Ipv6Addr;
use std::sync::{Arc, Mutex, MutexGuard, PoisonError};

use crate::{
    Result,
    error::Error,
    meshcop::{
        self, CoapCode, CoapMessage, CoapType, CommissionerOperation, MeshcopState,
        TLV_COMMISSIONER_SESSION_ID, TLV_STATE,
        util::{append_tlv_u8_length as append_tlv, append_u16_u8_length as append_u16},
    },
};

/// One observed request sent by a public commissioner method.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ObservedRequest {
    /// Logical operation selected by the public API method.
    pub operation: CommissionerOperation,
    /// Decoded CoAP request generated by the production request builder.
    ///
    /// For proxied operations this is the outer UDP_TX.ntf message; the inner
    /// request can be recovered with [`crate::meshcop::parse_udp_rx`]-style
    /// decapsulation via [`ObservedRequest::inner_message`].
    pub message: CoapMessage,
}

impl ObservedRequest {
    /// Returns the proxied inner request when `message` is a UDP_TX.ntf.
    pub fn inner_message(&self) -> Option<CoapMessage> {
        let tlvs = crate::tlv::TlvSet::parse(&self.message.payload).ok()?;
        let encapsulation = tlvs.last_value(meshcop::TLV_UDP_ENCAPSULATION)?;
        CoapMessage::decode(encapsulation.get(4..)?).ok()
    }

    /// Returns the UDP_TX destination address when `message` is a UDP_TX.ntf.
    pub fn proxy_destination(&self) -> Option<Ipv6Addr> {
        let tlvs = crate::tlv::TlvSet::parse(&self.message.payload).ok()?;
        let address = tlvs.last_value(meshcop::TLV_IPV6_ADDRESS)?;
        let octets: [u8; 16] = address.try_into().ok()?;
        Some(Ipv6Addr::from(octets))
    }
}

/// A scripted MeshCoP exchange expected by the harness.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ScriptedExchange {
    operation: CommissionerOperation,
    responses: Vec<ScriptedResponse>,
}

impl ScriptedExchange {
    /// Expects `operation` and delivers `responses` as the incoming stream.
    ///
    /// Empty ACK responses are consumed by the same loop the live path uses and
    /// therefore do not complete the public API call. When the request is
    /// proxied (UDP_TX), response templates are delivered in UDP_RX from the
    /// request's mesh destination, as a Thread device's answer would be;
    /// [`ScriptedResponse::Raw`] and [`ScriptedResponse::UdpRx`] are delivered
    /// as given.
    pub fn new(
        operation: CommissionerOperation,
        responses: impl IntoIterator<Item = ScriptedResponse>,
    ) -> Self {
        Self {
            operation,
            responses: responses.into_iter().collect(),
        }
    }
}

/// Response template used by a scripted exchange.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ScriptedResponse {
    /// An empty ACK matching the request message ID.
    EmptyAck,
    /// A CoAP Changed response with the supplied MeshCoP payload.
    Changed {
        /// Response payload.
        payload: Vec<u8>,
        /// Whether the response should be confirmable.
        confirmable: bool,
    },
    /// A CoAP Content response with the supplied payload.
    Content {
        /// Response payload.
        payload: Vec<u8>,
        /// Whether the response should be confirmable.
        confirmable: bool,
    },
    /// A response with an arbitrary CoAP code (token/message-ID echoed from the
    /// request), for negative tests such as error-coded responses.
    Coded {
        /// Response code.
        code: CoapCode,
        /// Response payload.
        payload: Vec<u8>,
    },
    /// A raw message for negative tests, such as token mismatches.
    Raw(CoapMessage),
    /// An empty Reset rejecting the request's message ID.
    Reset,
    /// The border agent closes the DTLS session with `close_notify` instead
    /// of answering.
    PeerClosed,
    /// Receiving fails as if the socket reported an error, for example an
    /// ICMP port-unreachable after the border agent went away.
    TransportFailure,
    /// A response wrapped in a UDP_RX.ntf encapsulation.
    ///
    /// The inner template is rendered against the request encapsulated in the
    /// observed UDP_TX.ntf so tokens and message IDs mirror the proxied
    /// request, exactly like a Thread device answering through the border
    /// agent proxy.
    UdpRx {
        /// Source address reported by the UDP_RX encapsulation.
        source_address: Ipv6Addr,
        /// Source port reported by the UDP_RX encapsulation.
        source_port: u16,
        /// Destination port reported by the UDP_RX encapsulation.
        destination_port: u16,
        /// Inner response template.
        inner: Box<ScriptedResponse>,
    },
}

impl ScriptedResponse {
    /// Creates an empty ACK response.
    pub const fn empty_ack() -> Self {
        Self::EmptyAck
    }

    /// Creates an empty Reset rejecting the request.
    pub const fn reset() -> Self {
        Self::Reset
    }

    /// Creates an accepting Changed response.
    pub fn accept() -> Self {
        Self::changed(state_payload(MeshcopState::Accept), false)
    }

    /// Creates a rejecting Changed response.
    pub fn reject() -> Self {
        Self::changed(state_payload(MeshcopState::Reject), false)
    }

    /// Creates a pending Changed response.
    pub fn pending() -> Self {
        Self::changed(state_payload(MeshcopState::Pending), false)
    }

    /// Creates an accepting petition response with a commissioner session ID.
    pub fn petition_accept(session_id: u16) -> Self {
        let mut payload = state_payload(MeshcopState::Accept);
        append_u16(&mut payload, TLV_COMMISSIONER_SESSION_ID, session_id);
        Self::changed(payload, false)
    }

    /// Creates an accepting petition response that also echoes the petitioner's
    /// Commissioner ID, as real Thread border agents do. The echoed ID is not a
    /// conflict — the petition is still accepted.
    pub fn petition_accept_with_id(session_id: u16, commissioner_id: &str) -> Self {
        let mut payload = state_payload(MeshcopState::Accept);
        append_u16(&mut payload, TLV_COMMISSIONER_SESSION_ID, session_id);
        append_tlv(
            &mut payload,
            crate::meshcop::TLV_COMMISSIONER_ID,
            commissioner_id.as_bytes(),
        );
        Self::changed(payload, false)
    }

    /// Creates a rejecting petition response with an existing commissioner ID.
    pub fn petition_reject(existing_commissioner_id: &str) -> Self {
        let mut payload = state_payload(MeshcopState::Reject);
        append_tlv(
            &mut payload,
            crate::meshcop::TLV_COMMISSIONER_ID,
            existing_commissioner_id.as_bytes(),
        );
        Self::changed(payload, false)
    }

    /// Creates a Changed response without a State TLV.
    pub fn changed_without_state() -> Self {
        Self::changed(Vec::new(), false)
    }

    /// Creates a non-confirmable Changed response with `payload`.
    pub fn changed(payload: Vec<u8>, confirmable: bool) -> Self {
        Self::Changed {
            payload,
            confirmable,
        }
    }

    /// Creates a non-confirmable Content response with `payload`.
    pub fn content(payload: Vec<u8>) -> Self {
        Self::Content {
            payload,
            confirmable: false,
        }
    }

    /// Wraps `inner` in a UDP_RX encapsulation from `source_address`.
    pub fn proxied(source_address: Ipv6Addr, inner: ScriptedResponse) -> Self {
        Self::UdpRx {
            source_address,
            source_port: meshcop::DEFAULT_MM_PORT,
            destination_port: meshcop::DEFAULT_MM_PORT,
            inner: Box::new(inner),
        }
    }

    /// Whether a Thread device would send this template, so that it travels
    /// back through the proxy when answering a proxied request.
    const fn is_device_answer(&self) -> bool {
        matches!(
            self,
            Self::EmptyAck
                | Self::Changed { .. }
                | Self::Content { .. }
                | Self::Coded { .. }
                | Self::Reset
        )
    }

    /// Renders this template against the logical (decapsulated) request so
    /// response tokens and message IDs mirror what a Thread device would echo.
    fn into_message(self, logical_request: &CoapMessage) -> Result<CoapMessage> {
        Ok(match self {
            Self::EmptyAck => CoapMessage::empty_ack(logical_request.message_id),
            Self::Changed {
                payload,
                confirmable,
            } => response(logical_request, CoapCode::CHANGED, payload, confirmable),
            Self::Content {
                payload,
                confirmable,
            } => response(logical_request, CoapCode::CONTENT, payload, confirmable),
            Self::Coded { code, payload } => response(logical_request, code, payload, false),
            Self::Raw(message) => message,
            Self::Reset => {
                let mut reset = CoapMessage::empty_ack(logical_request.message_id);
                reset.ty = CoapType::Reset;
                reset
            }
            Self::PeerClosed | Self::TransportFailure => {
                return Err(Error::InvalidState(
                    "a scripted connection event is not a message",
                ));
            }
            Self::UdpRx {
                source_address,
                source_port,
                destination_port,
                inner,
            } => {
                let inner_message = inner.into_message(logical_request)?;
                udp_rx_message(
                    source_address,
                    source_port,
                    destination_port,
                    &inner_message.encode()?,
                )?
            }
        })
    }
}

/// Extracts the inner request from an observed UDP_TX.ntf message.
///
/// Falls back to the outer message for direct exchanges so raw and
/// notification templates can be scripted on any route.
fn decapsulated_request(request: &CoapMessage) -> Result<CoapMessage> {
    let tlvs = crate::tlv::TlvSet::parse(&request.payload)?;
    match tlvs.last_value(meshcop::TLV_UDP_ENCAPSULATION) {
        Some(encapsulation) if encapsulation.len() >= 4 => CoapMessage::decode(&encapsulation[4..]),
        _ => Ok(request.clone()),
    }
}

/// Returns the mesh destination address and port of a UDP_TX.ntf request.
fn proxy_destination(request: &CoapMessage) -> Option<(Ipv6Addr, u16)> {
    let tlvs = crate::tlv::TlvSet::parse(&request.payload).ok()?;
    let address: [u8; 16] = tlvs
        .last_value(meshcop::TLV_IPV6_ADDRESS)?
        .try_into()
        .ok()?;
    let encapsulation = tlvs.last_value(meshcop::TLV_UDP_ENCAPSULATION)?;
    let port = u16::from_be_bytes(encapsulation.get(2..4)?.try_into().ok()?);
    Some((Ipv6Addr::from(address), port))
}

/// Builds a UDP_RX.ntf message carrying `inner` bytes.
pub fn udp_rx_message(
    source_address: Ipv6Addr,
    source_port: u16,
    destination_port: u16,
    inner: &[u8],
) -> Result<CoapMessage> {
    let mut encapsulation = Vec::with_capacity(4 + inner.len());
    encapsulation.extend_from_slice(&source_port.to_be_bytes());
    encapsulation.extend_from_slice(&destination_port.to_be_bytes());
    encapsulation.extend_from_slice(inner);

    let mut payload = Vec::new();
    append_tlv(
        &mut payload,
        meshcop::TLV_IPV6_ADDRESS,
        &source_address.octets(),
    );
    append_tlv(&mut payload, meshcop::TLV_UDP_ENCAPSULATION, &encapsulation);
    CoapMessage::post_request(
        CoapType::NonConfirmable,
        0x7a7a,
        Vec::new(),
        meshcop::uri::UDP_RX,
        payload,
    )
}

/// Scripted post-DTLS MeshCoP transport.
///
/// Clones share one script, so a test can keep a clone to inspect what the
/// session sent while the session's driver consumes the script.
#[derive(Debug, Clone, Default)]
pub struct ScriptedMeshcopTransport {
    state: Arc<Mutex<ScriptState>>,
    /// Wakes a session waiting for incoming messages.
    arrived: Arc<tokio::sync::Notify>,
}

#[derive(Debug, Default)]
struct ScriptState {
    exchanges: VecDeque<ScriptedExchange>,
    observed_requests: Vec<ObservedRequest>,
    sent_messages: Vec<CoapMessage>,
    incoming: VecDeque<ScriptedIncoming>,
    sends_fail: bool,
}

/// What the client receives next from the scripted border agent.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) enum ScriptedIncoming {
    /// A MeshCoP message.
    Message(CoapMessage),
    /// The border agent closed the DTLS session.
    PeerClosed,
    /// The socket reported an error.
    TransportFailure,
}

impl ScriptedMeshcopTransport {
    /// Creates a transport from the ordered exchange script.
    pub fn new(exchanges: impl IntoIterator<Item = ScriptedExchange>) -> Self {
        Self {
            state: Arc::new(Mutex::new(ScriptState {
                exchanges: exchanges.into_iter().collect(),
                ..ScriptState::default()
            })),
            arrived: Arc::default(),
        }
    }

    fn state(&self) -> MutexGuard<'_, ScriptState> {
        self.state.lock().unwrap_or_else(PoisonError::into_inner)
    }

    /// Returns requests observed so far.
    pub fn observed_requests(&self) -> Vec<ObservedRequest> {
        self.state().observed_requests.clone()
    }

    /// Returns every message the client sent outside of exchanges, such as
    /// ACKs for confirmable responses, proxied acknowledgements, relayed
    /// joiner records, and retransmissions.
    pub fn sent_messages(&self) -> Vec<CoapMessage> {
        self.state().sent_messages.clone()
    }

    /// Returns confirmable response message IDs for which the client generated
    /// an empty ACK.
    pub fn acked_confirmable_responses(&self) -> Vec<u16> {
        self.state()
            .sent_messages
            .iter()
            .filter(|message| {
                message.ty == CoapType::Acknowledgement && message.code == CoapCode::EMPTY
            })
            .map(|message| message.message_id)
            .collect()
    }

    /// Returns the number of exchanges not yet consumed.
    pub fn remaining_exchange_count(&self) -> usize {
        self.state().exchanges.len()
    }

    /// Delivers `message` to the session now, as if the border agent had just
    /// sent it; for answers that depend on a request's assigned identity or
    /// must arrive at a chosen time.
    pub fn deliver(&self, message: CoapMessage) {
        self.state()
            .incoming
            .push_back(ScriptedIncoming::Message(message));
        self.arrived.notify_one();
    }

    /// Waits until a message may have been delivered.
    pub(crate) async fn arrival(&self) {
        self.arrived.notified().await;
    }

    /// Makes every later send fail with an I/O error, as a socket does once
    /// the network path is gone.
    pub fn fail_sends(&self) {
        self.state().sends_fail = true;
    }

    fn check_send(&self) -> Result<()> {
        if self.state().sends_fail {
            return Err(Error::Io(std::io::Error::other("scripted send failure")));
        }
        Ok(())
    }

    /// Records a non-exchange message sent by the client.
    pub(crate) fn record_sent(&self, message: CoapMessage) -> Result<()> {
        self.check_send()?;
        self.state().sent_messages.push(message);
        Ok(())
    }

    /// Takes the next scripted message for the client to receive.
    pub(crate) fn next_incoming(&self) -> Option<ScriptedIncoming> {
        self.state().incoming.pop_front()
    }

    /// Consumes the next scripted exchange for a new request and queues its
    /// responses for the client to receive.
    ///
    /// The request's URI (after UDP_TX decapsulation) must match the scripted
    /// operation's URI.
    pub(crate) fn exchange(&self, request: &CoapMessage) -> Result<()> {
        self.check_send()?;
        let encoded = request.encode()?;
        let request = CoapMessage::decode(&encoded)?;
        let logical_request = decapsulated_request(&request)?;
        let proxy = proxy_destination(&request);
        let mut state = self.state();
        let exchange = state
            .exchanges
            .pop_front()
            .ok_or(Error::InvalidState("scripted MeshCoP exchange missing"))?;
        if logical_request.uri_path()?.as_deref() != Some(exchange.operation.uri_path()) {
            return Err(Error::InvalidState("scripted MeshCoP operation mismatch"));
        }
        state.observed_requests.push(ObservedRequest {
            operation: exchange.operation,
            message: request,
        });
        for template in exchange.responses {
            match template {
                ScriptedResponse::PeerClosed => {
                    state.incoming.push_back(ScriptedIncoming::PeerClosed);
                    continue;
                }
                ScriptedResponse::TransportFailure => {
                    state.incoming.push_back(ScriptedIncoming::TransportFailure);
                    continue;
                }
                _ => {}
            }
            let template = match proxy {
                Some((address, port)) if template.is_device_answer() => ScriptedResponse::UdpRx {
                    source_address: address,
                    source_port: port,
                    destination_port: meshcop::DEFAULT_MM_PORT,
                    inner: Box::new(template),
                },
                _ => template,
            };
            let message = template.into_message(&logical_request)?;
            // Round-trip through the wire form so the client sees exactly what
            // a live border agent would deliver.
            let delivered = CoapMessage::decode(&message.encode()?)?;
            state
                .incoming
                .push_back(ScriptedIncoming::Message(delivered));
        }
        self.arrived.notify_one();
        Ok(())
    }
}

fn response(
    request: &CoapMessage,
    code: CoapCode,
    payload: Vec<u8>,
    confirmable: bool,
) -> CoapMessage {
    CoapMessage {
        ty: if confirmable {
            CoapType::Confirmable
        } else {
            CoapType::Acknowledgement
        },
        code,
        message_id: request.message_id,
        token: request.token.clone(),
        options: Vec::new(),
        payload,
    }
}

fn state_payload(state: MeshcopState) -> Vec<u8> {
    let mut payload = Vec::new();
    append_tlv(&mut payload, TLV_STATE, &[state.to_wire()]);
    payload
}

/// Wall-clock bound on any test run through [`run_with_deadline`], enforced
/// from outside the async runtime.
const WATCHDOG_LIMIT: std::time::Duration = std::time::Duration::from_secs(15);

/// Runs a test body under an async `deadline` and a wall-clock watchdog.
///
/// The deadline fails a test whose session stalls. The watchdog covers what
/// the deadline cannot: a session task that spins without yielding blocks the
/// runtime's timers, and one that never goes idle stops paused time from
/// advancing. If the body runs longer than 15 seconds of wall-clock time, the
/// watchdog aborts the test process, which the mutation gate reports as a
/// failure rather than a timeout. Unstable test scaffolding for this
/// workspace's suites; not a supported public API.
pub async fn run_with_deadline(
    deadline: std::time::Duration,
    body: impl std::future::Future<Output = ()>,
) {
    let (finished, watched) = std::sync::mpsc::channel::<()>();
    let test = std::thread::current()
        .name()
        .unwrap_or("unnamed test")
        .to_owned();
    std::thread::spawn(move || {
        if let Err(std::sync::mpsc::RecvTimeoutError::Timeout) =
            watched.recv_timeout(WATCHDOG_LIMIT)
        {
            eprintln!("{test} ran for more than {WATCHDOG_LIMIT:?}; aborting the test process");
            std::process::abort();
        }
    });
    // Boxed: wrapping large handshake futures would otherwise overflow the
    // test thread's stack.
    let outcome = tokio::time::timeout(deadline, Box::pin(body)).await;
    drop(finished);
    assert!(outcome.is_ok(), "test exceeded its deadline");
}
